/*
 * Generated by scripts/gen_osd_font.py - do not edit the table by hand.
 *
 * The glyph shapes live in that script in row-major form, which is how
 * every published 5x7 reference writes them and how a human can check them
 * at a glance. The transpose into this file's column-major layout is what
 * the script is for: doing it by hand once per glyph is how a font ends up
 * with one mirrored character that nobody notices for a month.
 */

#include "osd_font.h"

/*
 * Column-major, bit 0 = top row. Five bytes per glyph, leftmost column
 * first. See osd_font.h for why this layout and not row-major.
 */
static const uint8_t kGlyphs[][OSD_FONT_WIDTH] = {
    /* ' '      (SPACE) */ { 0x00, 0x00, 0x00, 0x00, 0x00 },
    /* '0'      (DIGIT_0) */ { 0x3E, 0x51, 0x49, 0x45, 0x3E },
    /* '1'      (DIGIT_1) */ { 0x00, 0x42, 0x7F, 0x40, 0x00 },
    /* '2'      (DIGIT_2) */ { 0x42, 0x61, 0x51, 0x49, 0x46 },
    /* '3'      (DIGIT_3) */ { 0x21, 0x41, 0x45, 0x4B, 0x31 },
    /* '4'      (DIGIT_4) */ { 0x18, 0x14, 0x12, 0x7F, 0x10 },
    /* '5'      (DIGIT_5) */ { 0x27, 0x45, 0x45, 0x45, 0x39 },
    /* '6'      (DIGIT_6) */ { 0x3C, 0x4A, 0x49, 0x49, 0x30 },
    /* '7'      (DIGIT_7) */ { 0x01, 0x71, 0x09, 0x05, 0x03 },
    /* '8'      (DIGIT_8) */ { 0x36, 0x49, 0x49, 0x49, 0x36 },
    /* '9'      (DIGIT_9) */ { 0x06, 0x49, 0x49, 0x29, 0x1E },
    /* 'A'      (LETTER_A) */ { 0x7E, 0x09, 0x09, 0x09, 0x7E },
    /* 'B'      (LETTER_B) */ { 0x7F, 0x49, 0x49, 0x49, 0x36 },
    /* 'C'      (LETTER_C) */ { 0x3E, 0x41, 0x41, 0x41, 0x22 },
    /* 'D'      (LETTER_D) */ { 0x7F, 0x41, 0x41, 0x22, 0x1C },
    /* 'E'      (LETTER_E) */ { 0x7F, 0x49, 0x49, 0x49, 0x41 },
    /* 'F'      (LETTER_F) */ { 0x7F, 0x09, 0x09, 0x09, 0x01 },
    /* 'G'      (LETTER_G) */ { 0x3E, 0x41, 0x49, 0x49, 0x7A },
    /* 'H'      (LETTER_H) */ { 0x7F, 0x08, 0x08, 0x08, 0x7F },
    /* 'I'      (LETTER_I) */ { 0x00, 0x41, 0x7F, 0x41, 0x00 },
    /* 'J'      (LETTER_J) */ { 0x30, 0x40, 0x40, 0x40, 0x3F },
    /* 'K'      (LETTER_K) */ { 0x7F, 0x08, 0x14, 0x22, 0x41 },
    /* 'L'      (LETTER_L) */ { 0x7F, 0x40, 0x40, 0x40, 0x40 },
    /* 'M'      (LETTER_M) */ { 0x7F, 0x02, 0x0C, 0x02, 0x7F },
    /* 'N'      (LETTER_N) */ { 0x7F, 0x02, 0x04, 0x08, 0x7F },
    /* 'O'      (LETTER_O) */ { 0x3E, 0x41, 0x41, 0x41, 0x3E },
    /* 'P'      (LETTER_P) */ { 0x7F, 0x09, 0x09, 0x09, 0x06 },
    /* 'Q'      (LETTER_Q) */ { 0x3E, 0x41, 0x51, 0x21, 0x5E },
    /* 'R'      (LETTER_R) */ { 0x7F, 0x09, 0x19, 0x29, 0x46 },
    /* 'S'      (LETTER_S) */ { 0x46, 0x49, 0x49, 0x49, 0x31 },
    /* 'T'      (LETTER_T) */ { 0x01, 0x01, 0x7F, 0x01, 0x01 },
    /* 'U'      (LETTER_U) */ { 0x3F, 0x40, 0x40, 0x40, 0x3F },
    /* 'V'      (LETTER_V) */ { 0x1F, 0x20, 0x40, 0x20, 0x1F },
    /* 'W'      (LETTER_W) */ { 0x7F, 0x20, 0x18, 0x20, 0x7F },
    /* 'X'      (LETTER_X) */ { 0x63, 0x14, 0x08, 0x14, 0x63 },
    /* 'Y'      (LETTER_Y) */ { 0x03, 0x04, 0x78, 0x04, 0x03 },
    /* 'Z'      (LETTER_Z) */ { 0x61, 0x51, 0x49, 0x45, 0x43 },
    /* '-'      (MINUS) */ { 0x08, 0x08, 0x08, 0x08, 0x08 },
    /* '+'      (PLUS) */ { 0x08, 0x08, 0x3E, 0x08, 0x08 },
    /* '.'      (DOT) */ { 0x00, 0x60, 0x60, 0x00, 0x00 },
    /* ','      (COMMA) */ { 0x00, 0x70, 0x30, 0x00, 0x00 },
    /* ':'      (COLON) */ { 0x00, 0x36, 0x36, 0x00, 0x00 },
    /* '/'      (SLASH) */ { 0x60, 0x10, 0x08, 0x04, 0x03 },
    /* '%'      (PERCENT) */ { 0x63, 0x13, 0x08, 0x64, 0x63 },
    /* '='      (EQUAL) */ { 0x14, 0x14, 0x14, 0x14, 0x14 },
    /* '!'      (BANG) */ { 0x00, 0x00, 0x5F, 0x00, 0x00 },
    /* '?'      (QUEST) */ { 0x02, 0x01, 0x51, 0x09, 0x06 },
    /* '('      (LPAREN) */ { 0x00, 0x1C, 0x22, 0x41, 0x00 },
    /* ')'      (RPAREN) */ { 0x00, 0x41, 0x22, 0x1C, 0x00 },
    /* '['      (LBRACK) */ { 0x00, 0x7F, 0x41, 0x41, 0x00 },
    /* ']'      (RBRACK) */ { 0x00, 0x41, 0x41, 0x7F, 0x00 },
    /* '<'      (LT ) */ { 0x08, 0x14, 0x22, 0x41, 0x00 },
    /* '>'      (GT ) */ { 0x00, 0x41, 0x22, 0x14, 0x08 },
    /* '*'      (STAR) */ { 0x2A, 0x1C, 0x3E, 0x1C, 0x2A },
    /* '_'      (UNDER) */ { 0x40, 0x40, 0x40, 0x40, 0x40 },
    /* '~'      (DEGREE) */ { 0x06, 0x09, 0x09, 0x06, 0x00 },
    /* '?'      (LETTER_) */ { 0x40, 0x40, 0x40, 0x40, 0x40 },
};

/*
 * The lookup table. One entry per printable ASCII character, indexed by
 * (c - 32), giving an index into kGlyphs.
 *
 * Indexed rather than searched because the renderer asks for a glyph once
 * per character per frame, and a linear scan over sixty entries thirty
 * times a second is a silly amount of work for a font that never changes.
 *
 * Generated from the same table as the glyphs, so the two cannot drift. A
 * character the font does not have maps to the placeholder rather than
 * failing, and lowercase maps to the uppercase glyph - a 5x7 cell has no
 * room for real descenders, and pretending otherwise produces mush.
 */
static const uint8_t kAsciiIndex[96] = {
     0, 45, 46, 46, 46, 43, 46, 46, /* ' '  !  "  #  $  %  &  ' */
    47, 48, 53, 38, 40, 37, 39, 42, /*  (  )  *  +  ,  -  .  / */
     1,  2,  3,  4,  5,  6,  7,  8, /*  0  1  2  3  4  5  6  7 */
     9, 10, 41, 46, 51, 44, 52, 46, /*  8  9  :  ;  <  =  >  ? */
    46, 11, 12, 13, 14, 15, 16, 17, /*  @  A  B  C  D  E  F  G */
    18, 19, 20, 21, 22, 23, 24, 25, /*  H  I  J  K  L  M  N  O */
    26, 27, 28, 29, 30, 31, 32, 33, /*  P  Q  R  S  T  U  V  W */
    34, 35, 36, 49, 46, 50, 46, 54, /*  X  Y  Z  [  \  ]  ^  _ */
    46, 11, 12, 13, 14, 15, 16, 17, /*  `  a  b  c  d  e  f  g */
    18, 19, 20, 21, 22, 23, 24, 25, /*  h  i  j  k  l  m  n  o */
    26, 27, 28, 29, 30, 31, 32, 33, /*  p  q  r  s  t  u  v  w */
    34, 35, 36, 47, 45, 48, 55, 46, /*  x  y  z  {  |  }  ~   */
};

const struct osd_glyph *osd_font_lookup(char c)
{
    unsigned char uc = (unsigned char)c;
    int index;

    if (uc < 32U || uc > 127U) {
        return NULL;
    }

    index = kAsciiIndex[uc - 32U];
    return (const struct osd_glyph *)kGlyphs[index];
}

size_t osd_font_text_width(const char *text)
{
    size_t glyphs = 0U;

    if (text == NULL || text[0] == '\0') {
        return 0U;
    }

    /*
     * Every character advances, including ones the font does not know,
     * so a line's width does not change when a value happens to contain
     * an unsupported symbol. The trailing 1px separator is dropped.
     */
    while (text[glyphs] != '\0') {
        glyphs++;
    }

    return glyphs * (size_t)OSD_FONT_ADVANCE - 1U;
}

size_t osd_font_line_height(void)
{
    return (size_t)OSD_FONT_HEIGHT;
}

